### ISSUE TITLE
Lumma Stealer user agent 

### ISSUE THREAD

**Issue by ghvbn0** [mthcht/awesome-lists#12]
Hi

I just did some research of Lumma Stealer and it is using outdated chrome user agent 

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

Maybe it's worth to add to the list? :) 

Reference:
https://www.joesandbox.com/analysis/1575805/0/html
https://www.joesandbox.com/analysis/1575811/0/html
https://www.joesandbox.com/analysis/1576050/0/html

**Comment by mthcht** [comment]
Hi @ghvbn0,

Thanks for the suggestion! I’ve added a few exceptions to my list for very old valid user-agents. However, I see this approach more as compliance detection with a high false positive rate. Including valid user-agents that are just a few years old would require maintaining an extensive list, covering various malwares and tools, which could make it impractical for users relying on this list. Instead, I believe creating a dedicated detection rule specifically for compliance checks of old user-agents is a better approach, as I’ve outlined here: https://detect.fyi/threat-hunting-suspicious-user-agents-3dd764470bd0.

That said, this specific user-agent will be relevant in a threat hunting session focused on Lumma Stealer.

**Comment by ghvbn0** [comment]
Hey! 

Fair enough, thanks for further explanation, it makes sense :)
