### ISSUE TITLE
Add ports to suspicious file ?

### ISSUE THREAD

**Issue by JL2014** [mthcht/awesome-lists#6]
Hi,

what do you think about 9936 and 9966 ports mentionned with MoonPeak ?
need to add them on Lists/suspicious_ports_list.csv file ?

cited for example on https://thecyberexpress.com/north-korean-hackers-new-moonpeak-uat-5394/

Greetings, JL.

**Comment by mthcht** [comment]
Hello @JL2014, thanks for your input! The destination ports have been added: https://github.com/mthcht/awesome-lists/commit/c320a0dc686ddb7027a471b64807bced451aebe0 While there may be some legitimate services using these ports, like this Cisco device https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cucm/admin/12_5_1SU3/systemConfig/cucm_b_system-configuration-guide-1251su3/cucm_m_tcp-and-udp-port-usage-12-0.html and maybe QuickTime Streaming services (not sure) I've categorized them under the hunting category !
