### ISSUE TITLE
Cloud Intel: Public Cloud Threat intelligence platform 

### ISSUE THREAD

**Issue by unknownhad** [mthcht/awesome-lists#7]
May be you can add this as cLoud intelligence platform.
https://cloudintel.info/
The list is upated over here : https://github.com/unknownhad/CloudIntel
The full list of malicious IPs (Updated daily) is available by API.

**Comment by mthcht** [comment]
@unknownhad nice thanks ! added here https://github.com/mthcht/awesome-lists/commit/36c389bacdd4b797551ca49767e4471568348d08
